### ISSUE TITLE
Use expression as default for message

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaGPU/NVTX.jl#38]
It would be nice if `NVTX.range` used the expression as a default message. For example:

```julia
macro nvtx_expr(expr)
    return quote
        NVTX.@range string(expr) begin
            $(esc(expr))
        end
    end
end
```
So that,

```julia
a = rand(3);
NVTX.@range begin
    @. a = a
end
```
is shorthand for 
```julia
a = rand(3);
NVTX.@range "a .= a" begin
    @. a = a
end
```
Users can always change it themselves. Alternatively, we could add another macro?

**Comment by simonbyrne** [comment]
The default is `file:lineno`, but we could make it `expr file:lineno`
