### ISSUE TITLE
Naming threads: include MPI rank information

### ISSUE THREAD

**Issue by carstenbauer** [JuliaGPU/NVTX.jl#6]
I like [`NVTX.name_threads_julia()`](https://github.com/simonbyrne/NVTX.jl/blob/main/src/NVTX.jl#L244) but in a MPI + Threads application it would be nice to also include the MPI rank information (which is shown by default but is lost when calling the function). We probably can't do it without adding MPI.jl as a dependency though (which we likely don't want to do?)....

**Comment by simonbyrne** [comment]
I thought the process still keeps the MPI name?

**Comment by carstenbauer** [comment]
It didn't for me (I think). But I'll check again.

**Comment by simonbyrne** [comment]
In #31, I modified it so that `name_threads_julia` now takes a function you can use to set the name.
